In [10]:
import pandas as pd
import numpy as np

In [15]:
char = "Data/CharYelp2.csv"

In [19]:
char_pd = pd.read_csv(char)
char_pd.head(5)

,id,alias,name,image_url,is_closed,url,review_count,categories/0/alias,categories/0/title,rating,...,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49
0,yrUDeng1LrDvgyyjI5GiHA,pho-quynh-charlotte,Pho Quynh,https://s3-media4.fl.yelpcdn.com/bphoto/MnKklw...,False,https://www.yelp.com/biz/pho-quynh-charlotte?a...,43.0,vietnamese,Vietnamese,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PqcOSnCsJTT9Yd2xWKIMWw,la-shish-kabob-charlotte,La Shish Kabob,https://s3-media2.fl.yelpcdn.com/bphoto/Omf3DF...,False,https://www.yelp.com/biz/la-shish-kabob-charlo...,298.0,mideastern,Middle Eastern,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LdhprCGxa0inFo5P812EIg,loft-and-cellar-charlotte,Loft & Cellar,https://s3-media2.fl.yelpcdn.com/bphoto/dOSRTq...,False,https://www.yelp.com/biz/loft-and-cellar-charl...,55.0,cocktailbars,Cocktail Bars,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VH3WA7a-OVzFj2K_SP4BIw,the-kings-kitchen-charlotte,The King's Kitchen,https://s3-media2.fl.yelpcdn.com/bphoto/wGKQhL...,False,https://www.yelp.com/biz/the-kings-kitchen-cha...,576.0,tradamerican,American (Traditional),4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,trAd97ig2agtkZl2cimOMQ,something-classic-cafe-charlotte,Something Classic Cafe,https://s3-media2.fl.yelpcdn.com/bphoto/kSy_l4...,False,https://www.yelp.com/biz/something-classic-caf...,27.0,newamerican,American (New),4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN